# Site
name: "Do's And Don'ts"
description: "Discover essential do's and don'ts for travel, safety, driving, and daily life. Stay informed with practical tips and expert insights for smart decisions."
logo: 'assets/images/do-logo.png'
favicon: 'assets/images/favicon-do.ico'
baseurl: ''
disqus: 'codingrhodes'
url: 'https://do-and-donts.github.io'
email: 'do.and.donts.info@gmail.com'
mailchimp-list: ''

include: ["_pages"]


# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    CodingRhodes:
      name:           Coding Rhodes
      site:           /
      avatar:         assets/images/Author-codingRhodes.webp
      bio:            "Hi, I am Coding Rhodes, the author of this article, Do let me know If you have any Questions"
      email:          CodingRhodes@gmail.com
      twitter:        https://x.com/CodingRhodes
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]